# This file was generated by GoReleaser. DO NOT EDIT.
cask "changes" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_darwin_amd64.zip"
      sha256 "a0ff0312720ba14438ce8e3c8b1c97ff8cce75aa0d02ae9b4fce50c6d96d97aa"
    end
    on_arm do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_darwin_arm64.zip"
      sha256 "394a77fc89ad83da7f16fa5aa308d4dbbbc88a5f9a1af44a12edff6d5f1ca61e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_linux_amd64.tar.gz"
      sha256 "6e0c59ffae7145b9c8490b44e38394ad7d5ceed63c900d6ffc6ad53f361244ea"
    end
    on_arm do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_linux_arm64.tar.gz"
      sha256 "60f821e0cefd8f6d0b62b0648b0663b6b7f165d6cd80cbf5c63e261b9c84461d"
    end
  end

  name "changes"
  desc "Fragment-driven changelog and release-note manager."
  homepage "https://github.com/codefactory-hub/changes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "changes"

  # No zap stanza required

  caveats <<~EOS
    This cask is generated by GoReleaser from public GitHub release assets.
    If the release artifacts are signed and notarized, remove the quarantine hook.
  EOS
end
