# This file was generated by GoReleaser. DO NOT EDIT.
cask "changes" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_darwin_amd64.zip"
      sha256 "d5f638990423ed472d95f8f3169c431f2a7d8a74af5b695aaf9515da0da308bc"
    end
    on_arm do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_darwin_arm64.zip"
      sha256 "4433f9d60613ef0bd9e7edf0b3877ba2839e36c9a73959e00ab9a06fef3f61c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_linux_amd64.tar.gz"
      sha256 "aac78e8d4833e73a1737ac5ad236a0b3744d2b6eef080016ba85f25f02e3108f"
    end
    on_arm do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_linux_arm64.tar.gz"
      sha256 "14aabb3e2202247bd9bb73f7216ff2723a624619a22d2028f0121ffa1f00b4dc"
    end
  end

  name "changes"
  desc "Fragment-driven changelog and release-note manager."
  homepage "https://github.com/codefactory-hub/changes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "changes"

  # No zap stanza required

  caveats <<~EOS
    This cask is generated by GoReleaser from public GitHub release assets.
    If the release artifacts are signed and notarized, remove the quarantine hook.
  EOS
end
