# This file was generated by GoReleaser. DO NOT EDIT.
cask "changes" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_darwin_amd64.zip"
      sha256 "7d9085ea8273f2bc9c1d95ee05b100bef5107df08ac0d056ddefc2d4f2e40158"
    end
    on_arm do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_darwin_arm64.zip"
      sha256 "ef1686097a6e4cadcd1ca8c612cf5eea545734cbd3442f6c78863a859ca7344e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_linux_amd64.tar.gz"
      sha256 "3a4ec99eb5b24b530b269930c5bc69222b1ab6fcc7be0c4c6f0eb934f74b3e21"
    end
    on_arm do
      url "https://github.com/codefactory-hub/changes/releases/download/v#{version}/changes_#{version}_linux_arm64.tar.gz"
      sha256 "dccf7f1310ee2add8542b0f7406b46ae690465a7dce044a687c1a7d3c0c79470"
    end
  end

  name "changes"
  desc "Fragment-driven changelog and release-note manager."
  homepage "https://github.com/codefactory-hub/changes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "changes"

  # No zap stanza required

  caveats <<~EOS
    This cask is generated by GoReleaser from public GitHub release assets.
    If the release artifacts are signed and notarized, remove the quarantine hook.
  EOS
end
